-- GENERATED by db::migrations::tests::schema_snapshot_is_current.
-- Do not edit by hand: change db/migrations/, run cargo test, commit the diff.
-- Consumers: apps/mcp-server test fixtures seed their SQLite from this file.

CREATE TABLE _schema_version (
            version INTEGER PRIMARY KEY,
            applied_at TEXT NOT NULL DEFAULT (datetime('now'))
        );

CREATE TABLE agent_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT NOT NULL CHECK (kind IN ('start_fix', 'run_scan')),
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    env_url TEXT NOT NULL,
    check_id TEXT,
    scope TEXT CHECK (scope IS NULL OR scope IN ('web', 'code', 'full')),
    agent_tool TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'requested'
        CHECK (status IN ('requested', 'running', 'fulfilled', 'failed', 'expired')),
    result_json TEXT,
    failure_detail TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE TABLE alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    env_url TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL,
    alert_id TEXT NOT NULL,
    severity TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    detail_json TEXT,
    occurred_at INTEGER NOT NULL,
    first_seen_at INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    viewed_at INTEGER,
    dismissed_at INTEGER
);

CREATE TABLE causal_link_observations (
    project_id          INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    cause_check_id      TEXT NOT NULL,
    effect_check_id     TEXT NOT NULL,
    observed_at         INTEGER NOT NULL,
    co_active           INTEGER NOT NULL,
    co_resolved         INTEGER NOT NULL,
    resolution_event_id INTEGER,
    FOREIGN KEY (resolution_event_id) REFERENCES events(id) ON DELETE SET NULL
);

CREATE TABLE connected_group_revisions (
    project_id INTEGER NOT NULL,
    env_url TEXT NOT NULL,
    check_id TEXT NOT NULL,
    state_revision INTEGER NOT NULL CHECK (state_revision >= 0),
    pulled_at INTEGER NOT NULL,
    PRIMARY KEY (project_id, env_url, check_id),
    FOREIGN KEY (project_id, env_url)
        REFERENCES connected_sites(project_id, env_url) ON DELETE CASCADE
);

CREATE TABLE connected_mutation_outbox (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,
    env_url TEXT NOT NULL,
    check_id TEXT NOT NULL,
    decision TEXT NOT NULL CHECK (
        decision IN ('reopen', 'snooze', 'ignore', 'block', 'claim_fixed')
    ),
    snooze_until INTEGER,
    block_reason TEXT,
    based_on_revision INTEGER NOT NULL CHECK (based_on_revision >= 0),
    idempotency_key TEXT NOT NULL UNIQUE CHECK (length(idempotency_key) > 0),
    decided_at INTEGER NOT NULL,
    conflicted_at INTEGER,
    conflict_state TEXT,
    conflict_revision INTEGER,
    UNIQUE (project_id, env_url, check_id),
    CHECK ((decision = 'snooze') = (snooze_until IS NOT NULL)),
    CHECK (block_reason IS NULL OR decision = 'block'),
    CHECK ((conflicted_at IS NULL) = (conflict_state IS NULL)),
    CHECK ((conflicted_at IS NULL) = (conflict_revision IS NULL)),
    FOREIGN KEY (project_id, env_url)
        REFERENCES connected_sites(project_id, env_url) ON DELETE CASCADE
);

CREATE TABLE connected_producer (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    installation_id TEXT NOT NULL CHECK (length(installation_id) > 0),
    submission_sequence INTEGER NOT NULL CHECK (submission_sequence >= 0),
    minted_at INTEGER NOT NULL
);

CREATE TABLE connected_site_watermarks (
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    env_url TEXT NOT NULL,
    event_sequence INTEGER NOT NULL CHECK (event_sequence >= 0),
    pulled_at INTEGER NOT NULL,
    PRIMARY KEY (project_id, env_url)
);

CREATE TABLE connected_sites (
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    env_url TEXT NOT NULL,
    site_id TEXT NOT NULL CHECK (length(site_id) > 0),
    connected_at INTEGER NOT NULL,
    bootstrapped_at INTEGER, fingerprint_key_version INTEGER NOT NULL DEFAULT 1, pending_key_version INTEGER, scope_synced_revision INTEGER NOT NULL DEFAULT 0
    CHECK (scope_synced_revision >= 0),
    PRIMARY KEY (project_id, env_url)
);

CREATE TABLE cross_project_pattern_index (
    check_id        TEXT PRIMARY KEY,
    project_count   INTEGER NOT NULL,
    latest_seen_ms  INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL
);

CREATE TABLE "dismissed_integration_hints" (
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    check_id TEXT NOT NULL,
    integration_type TEXT NOT NULL,
    dismissed_at INTEGER NOT NULL,
    PRIMARY KEY (project_id, check_id, integration_type)
);

CREATE TABLE engine_release_checks (
    engine_release TEXT NOT NULL,
    manifest_digest TEXT NOT NULL,
    check_id TEXT NOT NULL,
    -- Semantic compatibility hash; NULL means the producer has no versioned contract.
    contract TEXT,
    -- Execution-profile dimensions that must also match, as a JSON array.
    compare_on TEXT NOT NULL DEFAULT '[]',
    -- 1 when the id is a family PREFIX rather than a literal check id.
    family INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (engine_release, manifest_digest, check_id),
    FOREIGN KEY (engine_release, manifest_digest)
        REFERENCES engine_releases(engine_release, manifest_digest) ON DELETE CASCADE
);

CREATE TABLE engine_releases (
    engine_release TEXT NOT NULL,
    manifest_digest TEXT NOT NULL,
    manifest_schema INTEGER NOT NULL,
    canonicalizer INTEGER NOT NULL,
    crawl_profile INTEGER NOT NULL,
    recorded_at INTEGER NOT NULL,
    PRIMARY KEY (engine_release, manifest_digest)
);

CREATE TABLE environments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    label TEXT NOT NULL,
    environment TEXT NOT NULL DEFAULT 'production',
    source TEXT,
    last_scanned_at TEXT,
    UNIQUE(project_id, url)
);

CREATE TABLE events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'info',
    occurred_at_ms INTEGER NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    detail TEXT,
    source TEXT NOT NULL DEFAULT 'internal',
    source_id TEXT,
    metadata TEXT,
    UNIQUE(project_id, source, source_id)
);

CREATE TABLE fix_attempts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    env_url TEXT NOT NULL,
    check_id TEXT NOT NULL,
    agent_tool TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'briefed',
    brief_md TEXT NOT NULL DEFAULT '',
    agent_summary TEXT,
    failure_detail TEXT,
    verify_started_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    brief_fetched_at INTEGER
, target_kind TEXT NOT NULL DEFAULT 'group'
    CHECK(target_kind IN ('group', 'occurrence')), target_relative_path TEXT, target_line INTEGER, producer_rule TEXT, target_occurrence_count INTEGER);

CREATE TABLE historical_enrichments (
    work_item_id INTEGER NOT NULL,
    integration  TEXT NOT NULL,
    payload      TEXT NOT NULL,
    created_at   INTEGER NOT NULL,
    PRIMARY KEY (work_item_id, integration),
    FOREIGN KEY (work_item_id) REFERENCES work_items(id) ON DELETE CASCADE
);

CREATE TABLE integration_configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    integration_type TEXT NOT NULL,
    api_key TEXT,
    site_id TEXT,
    extra TEXT,
    enabled INTEGER NOT NULL DEFAULT 1,
    UNIQUE(project_id, integration_type)
);

CREATE TABLE integration_enrichment_cache (
    project_id    INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    integration   TEXT NOT NULL,
    signal_key    TEXT NOT NULL,
    payload_json  TEXT NOT NULL,
    refreshed_at  INTEGER NOT NULL,
    PRIMARY KEY (project_id, integration, signal_key)
);

CREATE TABLE issue_links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    check_id TEXT NOT NULL,
    run_id INTEGER NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    external_id TEXT NOT NULL,
    external_url TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    created_at TEXT NOT NULL,
    resolved_at TEXT
);

CREATE TABLE launch_proof_notes (
    project_id INTEGER NOT NULL,
    environment_url TEXT NOT NULL DEFAULT '',
    item_id TEXT NOT NULL,
    proof_text TEXT NOT NULL DEFAULT '',
    artifact_text TEXT NOT NULL DEFAULT '',
    verified_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (project_id, environment_url, item_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE launch_site_profiles (
    project_id INTEGER NOT NULL,
    environment_url TEXT NOT NULL DEFAULT '',
    overrides_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (project_id, environment_url),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE launch_snapshots (
    id TEXT PRIMARY KEY,
    project_id INTEGER NOT NULL,
    environment_url TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    checked_at TEXT,
    readiness TEXT NOT NULL,
    decision TEXT NOT NULL,
    decision_label TEXT NOT NULL,
    profile_kind_label TEXT NOT NULL,
    profile_confidence_label TEXT NOT NULL,
    stack_label TEXT NOT NULL,
    passing_checks INTEGER NOT NULL,
    total_checks INTEGER NOT NULL,
    score_percent INTEGER NOT NULL,
    open_blockers INTEGER NOT NULL,
    critical_open INTEGER NOT NULL,
    important_open INTEGER NOT NULL,
    owner_proof_open INTEGER NOT NULL,
    skipped_checks INTEGER NOT NULL,
    not_applicable_checks INTEGER NOT NULL,
    launch_code_risk_count INTEGER NOT NULL,
    source_mapped_checks INTEGER NOT NULL,
    top_blocker_json TEXT,
    used_surfaces_json TEXT NOT NULL,
    confirmed_not_used_surfaces_json TEXT NOT NULL,
    unknown_surfaces_json TEXT NOT NULL,
    snapshot_json TEXT NOT NULL,
    persisted_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE license_state (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            license_key TEXT NOT NULL,
            instance_id TEXT NOT NULL,
            variant_id INTEGER NOT NULL,
            tier TEXT NOT NULL DEFAULT 'free',
            status TEXT NOT NULL DEFAULT 'active',
            last_validated_at TEXT NOT NULL,
            activated_at TEXT NOT NULL,
            expires_at TEXT
        );

CREATE TABLE pages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    site_id INTEGER NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    path TEXT NOT NULL,
    title TEXT,
    last_seen_at TEXT NOT NULL DEFAULT (datetime('now')),
    source TEXT NOT NULL DEFAULT 'auto',
    UNIQUE(site_id, url)
);

CREATE TABLE "project_issue_states" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    env_url TEXT NOT NULL,
    check_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('new', 'snoozed', 'ignored', 'blocked', 'verified', 'regressed')),
    snooze_until INTEGER,
    block_reason TEXT,
    last_status_changed_at INTEGER NOT NULL,
    verified_by TEXT CHECK ((status = 'verified') = (verified_by IS NOT NULL)
        AND (verified_by IS NULL OR verified_by IN ('user_claim', 'local_scan')))
);

CREATE TABLE project_signal_snapshots (
    project_id INTEGER NOT NULL,
    environment_url TEXT NOT NULL DEFAULT '',
    monitoring_json TEXT,
    monitoring_refreshed_at TEXT,
    updates_json TEXT,
    updates_refreshed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (project_id, environment_url),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE project_ui_state (
    project_id INTEGER PRIMARY KEY,
    first_scan_banner_dismissed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    path TEXT NOT NULL DEFAULT '',
    framework TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    secret_namespace TEXT NOT NULL
);

CREATE TABLE regression_check_ids (
    regression_id INTEGER NOT NULL REFERENCES regressions(id) ON DELETE CASCADE,
    check_id TEXT NOT NULL,
    PRIMARY KEY (regression_id, check_id)
);

CREATE TABLE regressions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    env_url TEXT NOT NULL,
    scan_type TEXT NOT NULL CHECK (scan_type IN ('web', 'code')),
    prev_run_id INTEGER NOT NULL,
    run_id INTEGER NOT NULL,
    prev_score INTEGER NOT NULL,
    score INTEGER NOT NULL,
    commit_from TEXT NOT NULL,
    commit_to TEXT NOT NULL,
    commit_count INTEGER NOT NULL DEFAULT 0,
    commits_json TEXT NOT NULL DEFAULT '[]',
    fixed_check_ids_json TEXT NOT NULL DEFAULT '[]',
    created_at INTEGER NOT NULL,
    UNIQUE (scan_type, run_id)
);

CREATE TABLE report_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    site_url TEXT NOT NULL,
    period_days INTEGER NOT NULL,
    report_title TEXT NOT NULL DEFAULT 'Website Health Report',
    generated_at TEXT NOT NULL DEFAULT (datetime('now')),
    branding_json TEXT,
    sections_json TEXT,
    report_summary_json TEXT,
    output_format TEXT NOT NULL DEFAULT 'preview'
);

CREATE TABLE scan_executions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL,
    environment_id INTEGER REFERENCES environments(id) ON DELETE SET NULL,
    environment_url TEXT,
    environment_scope_key TEXT NOT NULL,
    requested_mode TEXT NOT NULL
        CHECK (requested_mode IN ('full', 'web', 'code')),
    web_focus TEXT
        CHECK (web_focus IS NULL OR web_focus IN
            ('health', 'security', 'accessibility', 'polish')),
    trigger TEXT NOT NULL
        CHECK (trigger IN
            ('manual', 'tray', 'scheduled', 'verification', 'background', 'migration')),
    admission_class TEXT NOT NULL
        CHECK (admission_class IN
            ('general_scan', 'bounded_verification', 'system_exempt')),
    status TEXT NOT NULL DEFAULT 'planned'
        CHECK (status IN
            ('planned', 'running', 'complete', 'partial', 'failed', 'cancelled')),
    idempotency_key TEXT NOT NULL UNIQUE,
    request_fingerprint TEXT NOT NULL,
    started_at INTEGER NOT NULL,
    completed_at INTEGER,
    score_snapshot_id INTEGER REFERENCES score_snapshots(id) ON DELETE SET NULL,
    failure_summary TEXT,
    legacy_provenance TEXT,
    web_status TEXT
        CHECK (web_status IS NULL OR web_status IN
            ('planned', 'running', 'complete', 'failed', 'cancelled', 'skipped')),
    web_detail TEXT,
    code_status TEXT
        CHECK (code_status IS NULL OR code_status IN
            ('planned', 'running', 'complete', 'failed', 'cancelled', 'skipped')),
    code_detail TEXT
, based_on_event_sequence INTEGER NOT NULL DEFAULT 0);

CREATE TABLE scan_findings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id INTEGER NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
    occurrence_id TEXT NOT NULL,
    source TEXT NOT NULL CHECK(source IN ('web_scan', 'code_scan')),
    canonical_check_id TEXT NOT NULL,
    producer_check_id TEXT NOT NULL,
    category TEXT NOT NULL,
    producer_category TEXT NOT NULL,
    domain TEXT,
    verdict TEXT NOT NULL CHECK(verdict IN ('pass', 'fail', 'warn', 'skipped')),
    severity TEXT NOT NULL CHECK(severity IN ('critical', 'high', 'medium', 'low')),
    confidence TEXT NOT NULL CHECK(confidence IN ('confirmed', 'high', 'needs_review')),
    confidence_reason TEXT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    fix_prompt TEXT,
    producer_fix_prompt TEXT,
    manual_fix TEXT,
    why_it_matters TEXT,
    verification_hint TEXT,
    raw_data TEXT,
    detail_json TEXT,
    location_kind TEXT NOT NULL CHECK(location_kind IN
        ('page', 'file', 'project', 'site', 'none')),
    page_url TEXT,
    relative_path TEXT,
    line INTEGER,
    UNIQUE(run_id, ordinal),
    UNIQUE(run_id, occurrence_id)
);

CREATE TABLE scan_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    execution_id INTEGER NOT NULL REFERENCES scan_executions(id) ON DELETE CASCADE,
    parent_run_id INTEGER REFERENCES scan_runs(id) ON DELETE CASCADE,
    project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL,
    site_id INTEGER REFERENCES sites(id) ON DELETE SET NULL,
    environment_url TEXT,
    environment_scope_key TEXT NOT NULL,
    source TEXT NOT NULL CHECK(source IN ('web_scan', 'code_scan')),
    run_kind TEXT NOT NULL CHECK(run_kind IN ('single', 'multi_parent', 'page', 'code')),
    status TEXT NOT NULL CHECK(status IN
        ('planned', 'running', 'complete', 'failed', 'cancelled', 'skipped')),
    focus TEXT,
    started_at INTEGER NOT NULL,
    completed_at INTEGER,
    timestamp_text TEXT NOT NULL,
    raw_score INTEGER,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    coverage_kind TEXT NOT NULL CHECK(coverage_kind IN
        ('site', 'page_set', 'page', 'project', 'check_set', 'rule_set')),
    coverage_json TEXT NOT NULL DEFAULT '{}',
    diagnostics_json TEXT,
    status_detail TEXT,
    detail_state TEXT NOT NULL DEFAULT 'exact'
        CHECK(detail_state IN ('exact', 'limited_legacy')),
    -- Web diagnostics.
    mode TEXT,
    security_score INTEGER,
    performance_score INTEGER,
    seo_score INTEGER,
    accessibility_score INTEGER,
    compliance_score INTEGER,
    config_score INTEGER,
    polish_score INTEGER,
    issues_total INTEGER NOT NULL DEFAULT 0,
    issues_critical INTEGER NOT NULL DEFAULT 0,
    issues_high INTEGER NOT NULL DEFAULT 0,
    issues_medium INTEGER NOT NULL DEFAULT 0,
    issues_low INTEGER NOT NULL DEFAULT 0,
    issues_passed INTEGER NOT NULL DEFAULT 0,
    detected_stack TEXT,
    page_url TEXT,
    total_pages INTEGER,
    completed_pages INTEGER,
    axe_enabled INTEGER,
    -- Code diagnostics.
    project_path TEXT,
    framework TEXT,
    -- Deterministic one-way-backfill provenance. New runs leave these NULL.
    legacy_source TEXT,
    legacy_id INTEGER, engine_release TEXT, manifest_digest TEXT, canonicalizer INTEGER, crawl_profile INTEGER, execution_profile_json TEXT, scope_revision INTEGER, code_commit_sha TEXT, code_tree_clean INTEGER
  CHECK (code_tree_clean IS NULL OR code_tree_clean IN (0, 1)),
    UNIQUE(legacy_source, legacy_id)
);

CREATE TABLE scan_schedules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    environment_id INTEGER NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
    frequency TEXT NOT NULL DEFAULT 'off' CHECK(frequency IN ('off', 'daily', 'weekly')),
    time_of_day TEXT NOT NULL DEFAULT '09:00',
    day_of_week INTEGER,
    -- Schedulable focuses (core::scanner::ScheduledScanType): the four web
    -- ScanType values, 'code' (routes to the Code Scan engine), and 'full'
    -- (a web scan plus a Code Scan, mirroring the manual runner).
    scan_type TEXT NOT NULL DEFAULT 'health' CHECK(scan_type IN ('health', 'security', 'accessibility', 'polish', 'code', 'full')),
    last_run_at TEXT,
    next_run_at TEXT,
    -- No now-based column defaults (guardrail: migrations after the baseline
    -- supply timestamps from Rust). Existing rows copy their values below; the
    -- only insert path, save_scan_schedule, sets created_at and updated_at.
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(project_id, environment_id, scan_type)
);

CREATE TABLE score_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    -- Normalized environment URL ('' when scored without an environment),
    -- matching the env scoping of the work_items the score reads.
    environment_url TEXT NOT NULL DEFAULT '',
    overall REAL NOT NULL,
    critical_count INTEGER NOT NULL DEFAULT 0,
    high_count INTEGER NOT NULL DEFAULT 0,
    medium_count INTEGER NOT NULL DEFAULT 0,
    low_count INTEGER NOT NULL DEFAULT 0,
    exploitable_capped INTEGER NOT NULL DEFAULT 0,
    computed_at INTEGER NOT NULL
);

CREATE TABLE signal_baselines (
    project_id   INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    signal_key   TEXT NOT NULL,
    window_days  INTEGER NOT NULL,
    mean         REAL NOT NULL,
    stddev       REAL NOT NULL,
    sample_count INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL,
    PRIMARY KEY (project_id, signal_key, window_days)
);

CREATE TABLE signal_history (
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    signal_key TEXT NOT NULL,
    ts_ms      INTEGER NOT NULL,
    value      REAL NOT NULL,
    PRIMARY KEY (project_id, signal_key, ts_ms)
);

CREATE TABLE "site_event_check_ids" (
    event_id INTEGER NOT NULL,
    check_id TEXT NOT NULL,
    PRIMARY KEY (event_id, check_id),
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE site_scan_scope (
    site_id INTEGER NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    route TEXT NOT NULL,
    position INTEGER NOT NULL,
    PRIMARY KEY (site_id, route)
);

CREATE TABLE site_verified_good (
    site_id INTEGER NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    field TEXT NOT NULL,
    good_value_json TEXT NOT NULL,
    good_digest TEXT NOT NULL,
    good_profile_version INTEGER NOT NULL,
    good_recorded_at INTEGER NOT NULL,
    good_source_scan_id INTEGER,
    good_origin TEXT NOT NULL
        CHECK(good_origin IN ('seeded', 'promoted', 'accepted', 'reseeded')),
    drift_value_json TEXT,
    drift_digest TEXT,
    drift_first_seen_at INTEGER,
    drift_last_seen_at INTEGER,
    drift_source_scan_id INTEGER,
    drift_dismissed INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (site_id, field)
);

CREATE TABLE sites (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    sitemap_url TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_scanned_at TEXT
, scope_revision INTEGER NOT NULL DEFAULT 0, scope_updated_at TEXT, profile_revision INTEGER NOT NULL DEFAULT 0);

CREATE TABLE trial_state (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    email TEXT NOT NULL,
    started_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    last_validated_at TEXT NOT NULL,
    validation_token TEXT,
    max_observed_at TEXT
);

CREATE TABLE webhook_configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    events TEXT NOT NULL DEFAULT '[]',
    secret TEXT,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(project_id, url)
);

CREATE TABLE work_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    env_url TEXT NOT NULL,
    source TEXT NOT NULL,
    signal_id TEXT NOT NULL,
    check_id TEXT NOT NULL,
    category TEXT NOT NULL,
    severity TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    detail_json TEXT,
    scan_ref INTEGER,
    first_seen_at INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    resolved_at INTEGER,
    page_url TEXT,
    fix_prompt TEXT,
    manual_fix TEXT,
    why_it_matters TEXT,
    -- Promoted metadata used by scoring and fix targeting; absent for unsupported sources.
    confidence TEXT,
    domain TEXT,
    relative_path TEXT,
    line INTEGER
, check_status TEXT
    CHECK (check_status IS NULL OR check_status IN ('pass', 'fail', 'warn', 'skipped')), confidence_reason TEXT, producer_check_id TEXT, producer_fix_prompt TEXT, producer_category TEXT
    CHECK (producer_category IS NULL OR producer_category IN
           ('security', 'performance', 'seo', 'accessibility', 'compliance', 'config', 'polish')), first_seen_scan_ref INTEGER, resolved_scan_ref INTEGER);

CREATE INDEX idx_agent_requests_status ON agent_requests (status, id);

CREATE INDEX idx_alerts_unread
    ON alerts(project_id, viewed_at, dismissed_at, occurred_at DESC);

CREATE UNIQUE INDEX uq_alerts_identity
    ON alerts(project_id, env_url, source, alert_id);

CREATE INDEX idx_observations_link
    ON causal_link_observations(project_id, cause_check_id, effect_check_id);

CREATE INDEX idx_engine_release_checks_release
    ON engine_release_checks(engine_release, manifest_digest);

CREATE INDEX idx_environments_project_id ON environments(project_id);

CREATE INDEX idx_events_occurred_at ON events(occurred_at_ms);

CREATE INDEX idx_events_project_id ON events(project_id);

CREATE INDEX idx_events_project_occurred
    ON events(project_id, occurred_at_ms DESC);

CREATE INDEX idx_events_project_type_occurred
    ON events(project_id, event_type, occurred_at_ms DESC);

CREATE INDEX idx_events_type ON events(event_type);

CREATE INDEX idx_fix_attempts_status ON fix_attempts(status);

CREATE UNIQUE INDEX uq_fix_attempts_active
    ON fix_attempts(
        project_id, env_url, check_id, target_kind,
        COALESCE(target_relative_path, ''), COALESCE(target_line, -1)
    )
    WHERE status IN ('briefed', 'verify_requested', 'verifying');

CREATE INDEX idx_iec_freshness
    ON integration_enrichment_cache(project_id, refreshed_at);

CREATE UNIQUE INDEX idx_issue_links_attempt_identity
    ON issue_links(project_id, check_id, run_id, provider);

CREATE INDEX idx_issue_links_project_check
    ON issue_links(project_id, check_id, provider);

CREATE INDEX idx_issue_links_run
    ON issue_links(run_id);

CREATE INDEX idx_issue_links_status
    ON issue_links(project_id, status);

CREATE INDEX idx_launch_proof_notes_project_env
    ON launch_proof_notes(project_id, environment_url);

CREATE INDEX idx_launch_site_profiles_project
    ON launch_site_profiles(project_id);

CREATE INDEX idx_launch_snapshots_project_decision
    ON launch_snapshots(project_id, decision, created_at DESC);

CREATE INDEX idx_launch_snapshots_project_env_created
    ON launch_snapshots(project_id, environment_url, created_at DESC);

CREATE INDEX idx_pages_site_id ON pages(site_id);

CREATE INDEX idx_project_issue_states_project_env
    ON project_issue_states(project_id, env_url);

CREATE UNIQUE INDEX uq_project_issue_states_identity
    ON project_issue_states(project_id, env_url, check_id);

CREATE INDEX idx_project_signal_snapshots_project
    ON project_signal_snapshots(project_id);

CREATE INDEX idx_project_ui_state_project
    ON project_ui_state(project_id);

CREATE UNIQUE INDEX idx_projects_secret_namespace
    ON projects(secret_namespace);

CREATE INDEX idx_regression_check_ids_by_check
    ON regression_check_ids(check_id, regression_id);

CREATE INDEX idx_regressions_project ON regressions(project_id);

CREATE INDEX idx_regressions_run ON regressions(scan_type, run_id);

CREATE INDEX idx_report_history_project ON report_history(project_id);

CREATE INDEX idx_scan_executions_history
    ON scan_executions(project_id, environment_scope_key, started_at DESC);

CREATE INDEX idx_scan_findings_check
    ON scan_findings(canonical_check_id, run_id);

CREATE INDEX idx_scan_findings_occurrence
    ON scan_findings(occurrence_id, run_id);

CREATE INDEX idx_scan_findings_run
    ON scan_findings(run_id, ordinal);

CREATE INDEX idx_scan_runs_code_provenance
  ON scan_runs (project_id, environment_scope_key, code_commit_sha)
  WHERE source = 'code_scan';

CREATE INDEX idx_scan_runs_execution
    ON scan_runs(execution_id, id);

CREATE INDEX idx_scan_runs_history
    ON scan_runs(project_id, environment_url, started_at DESC);

CREATE INDEX idx_scan_runs_parent
    ON scan_runs(parent_run_id, id);

CREATE INDEX idx_score_snapshots_project_env
    ON score_snapshots(project_id, environment_url, id);

CREATE INDEX idx_signal_history_window
    ON signal_history(project_id, signal_key, ts_ms);

CREATE INDEX idx_site_event_check_ids_by_check
    ON site_event_check_ids(check_id, event_id);

CREATE INDEX idx_site_scan_scope_site
    ON site_scan_scope(site_id, position);

CREATE INDEX idx_site_verified_good_site
    ON site_verified_good(site_id);

CREATE UNIQUE INDEX uq_sites_adhoc_url
    ON sites(url) WHERE project_id IS NULL;

CREATE UNIQUE INDEX uq_sites_project_url
    ON sites(project_id, url) WHERE project_id IS NOT NULL;

CREATE INDEX idx_work_items_active
    ON work_items(project_id, env_url, resolved_at);

CREATE INDEX idx_work_items_canonical_scan_ref
    ON work_items(source, scan_ref);

CREATE INDEX idx_work_items_check_id
    ON work_items(check_id);

CREATE INDEX idx_work_items_first_seen
    ON work_items(first_seen_at);

CREATE INDEX idx_work_items_page_url
    ON work_items(project_id, env_url, page_url)
    WHERE resolved_at IS NULL AND page_url IS NOT NULL;

CREATE INDEX idx_work_items_project_first_seen
    ON work_items(project_id, first_seen_at);

CREATE INDEX idx_work_items_resolved_scan_ref
    ON work_items(source, resolved_scan_ref)
    WHERE resolved_scan_ref IS NOT NULL;

CREATE INDEX idx_work_items_source_env_resolved
    ON work_items (source, env_url, resolved_at DESC)
    WHERE resolved_at IS NOT NULL;

CREATE INDEX idx_work_items_source_scan_ref
    ON work_items(source, scan_ref);

CREATE UNIQUE INDEX uq_work_items_active
    ON work_items(project_id, env_url, source, signal_id)
    WHERE resolved_at IS NULL;

